In [17]:
import pandas as pd
from pymongo import MongoClient, GEO2D
import time
import csv
import json
import pymongo
from sshtunnel import SSHTunnelForwarder
from bson.son import SON

In [18]:
foodRatings = pd.read_csv('../data/foodRatings.csv',encoding='latin-1')
pharmacies = pd.read_csv('../data/Pharmacy.csv',encoding='latin-1')
stations = pd.read_csv('../data/Station use.csv')
crime2 = pd.read_csv('../data/police/2017-02-hampshire-street.csv')
crime3 = pd.read_csv('../data/police/2017-03-hampshire-street.csv')
crime4 = pd.read_csv('../data/police/2017-04-hampshire-street.csv')
crime5 = pd.read_csv('../data/police/2017-05-hampshire-street.csv')
crime6 = pd.read_csv('../data/police/2017-06-hampshire-street.csv')
crime7 = pd.read_csv('../data/police/2017-07-hampshire-street.csv')
crime8 = pd.read_csv('../data/police/2017-08-hampshire-street.csv')
crime9 = pd.read_csv('../data/police/2017-09-hampshire-street.csv')
crimes = pd.concat([crime2,crime3,crime4,crime5,crime6,crime7,crime8,crime9])

In [76]:
MONGO_HOST = "167.99.88.178"
MONGO_PORT = 27017
MONGO_DB = "houseguru"
USER = "root"
PASS = "COMP6214CW2"

server = SSHTunnelForwarder(
    MONGO_HOST,
    ssh_username=USER,
    ssh_password=PASS,
    remote_bind_address=('0.0.0.0', 27017)
)

server.start()

con = pymongo.MongoClient(MONGO_HOST, MONGO_PORT)
db = con[MONGO_DB]
# db.authenticate(MONGO_USER, MONGO_PASS)
places = db.places
print(db)

Database(MongoClient(host=['167.99.88.178:27017'], document_class=dict, tz_aware=False, connect=True), 'houseguru')

In [68]:
def convert(dataframe,name,bistype,long,lat):
    dic = []
    for index, row in dataframe.iterrows():
        item = {
            "name":row[name],
            "type":bistype,
            "geocode":[row[long],row[lat]]
        }
        dic.append(item)
    return dic

In [74]:
def export(jsondoc,filename):
    file = open(filename+".json","w")
    json.dump(jsondoc,file)
    file.close()
    places.insert(jsondoc)

In [70]:
foodRatings.head()

,FHRSID,LocalAuthorityBusinessID,BusinessName,BusinessType,BusinessTypeID,AddressLine1,AddressLine2,PostCode,RatingValue,RatingKey,...,Scores/Hygiene,Scores/Structural,Scores/ConfidenceInManagement,SchemeType,NewRatingPending,Geocode/Longitude,Geocode/Latitude,AddressLine3,AddressLine4,RatingDate/_xsi:nil
0,706071,14930/0110/0/000,7 Bone Burger Co,Restaurant/Cafe/Canteen,1,110 Portswood Road,Southampton,SO17 2FW,3,fhrs_3_en-GB,...,10.0,10.0,10.0,FHRS,False,-1.395055,50.922154,NaN,NaN,NaN
1,219539,11170/0044/0/000,88 Chinese Restaurant,Restaurant/Cafe/Canteen,1,44 London Road,Southampton,SO15 2AH,5,fhrs_5_en-GB,...,5.0,5.0,5.0,FHRS,False,-1.403594,50.911947,NaN,NaN,NaN
2,219913,06/00072/FOOD,90 Degrees At Carltons,Restaurant/Cafe/Canteen,1,24 Carlton Place,Southampton,SO15 2DY,4,fhrs_4_en-GB,...,5.0,10.0,5.0,FHRS,False,-1.405177,50.912737,NaN,NaN,NaN
3,371607,09/00067/COMM,99p Stores Ltd,Retailers - other,4613,3 - 7 Shirley High Street,Southampton,SO15 3UL,5,fhrs_5_en-GB,...,5.0,5.0,5.0,FHRS,False,-1.439055,50.915312,NaN,NaN,NaN
4,220098,16850/7375/0/001,A T And P M Phillips,Retailers - other,4613,Outside,73-75 Shirley High Street,SO15 3NP,5,fhrs_5_en-GB,...,5.0,5.0,5.0,FHRS,False,-1.433506,50.922599,Southampton,NaN,NaN

In [75]:
jsondoc = convert(foodRatings,"BusinessName",'food','Geocode/Longitude','Geocode/Latitude')
export(jsondoc,'foodratings')

ServerSelectionTimeoutError: 167.99.88.178:27017: [Errno 60] Operation timed out

In [260]:
pharmacies.head()

                     OrganisationName   Latitude  Longitude
0                     Lords Pharmacy   52.244797   0.405598
1                Sainsbury's Pharmacy  54.895298  -2.945134
2                  Weldricks Pharmacy  53.512993  -1.132898
3        Rutland Late Night Pharmacy   52.669994  -0.730139
4  Stockport Pharmacy (Internet Only)  53.402050  -2.165045

In [ ]:
jsondoc = convert(pharmacies,"OrganisationName",'pharmacy','Longitude','Latitude')
export(jsondoc,'pharmacies')

In [263]:
crimes.head()

,Crime ID,Month,Reported by,Falls within,Longitude,Latitude,Location,LSOA code,LSOA name,Crime type,Last outcome category,Context
0,NaN,2017-02,Hampshire Constabulary,Hampshire Constabulary,-1.145148,51.353137,On or near Mount Pleasant,E01022553,Basingstoke and Deane 001A,Anti-social behaviour,NaN,NaN
1,NaN,2017-02,Hampshire Constabulary,Hampshire Constabulary,-1.143597,51.350797,On or near Willow Road,E01022553,Basingstoke and Deane 001A,Anti-social behaviour,NaN,NaN
2,NaN,2017-02,Hampshire Constabulary,Hampshire Constabulary,-1.143597,51.350797,On or near Willow Road,E01022553,Basingstoke and Deane 001A,Anti-social behaviour,NaN,NaN
3,b394fb7affc4a51fada38b4e01575c3861a03ebf5fd695...,2017-02,Hampshire Constabulary,Hampshire Constabulary,-1.146835,51.349633,On or near Sarisbury Close,E01022553,Basingstoke and Deane 001A,Public order,Unable to prosecute suspect,NaN
4,199e5bcf281894eb4d6830777cfe0eb93733375dcdf9f4...,2017-02,Hampshire Constabulary,Hampshire Constabulary,-1.147727,51.353443,On or near The Beeches,E01022553,Basingstoke and Deane 001A,Violence and sexual offences,Unable to prosecute suspect,NaN

In [266]:
dic = []
for index, row in crimes.iterrows():
    item = {
        "name":row['Crime type'],
        "type":'crime',
        'date':row['Month'],
        "geocode":[row['Longitude'],row['Latitude']]
    }
    dic.append(item)
export_json(dic,'crimes')

In [272]:
for doc in places.find({"geocode":float('nan')}):
    places.remove(doc)

In [273]:
places.create_index([("geocode",GEO2D)])

'geocode_2d'

In [274]:
query = {"geocode": SON([("$near", [2, 5]), ("$maxDistance", 100)])}
for doc in db.places.find(query).limit(30):
    pprint.pprint(doc)

{'_id': ObjectId('5aedd8ca6eca7e03326e8c8e'),
 'geocode': [-3.7669289112, 50.2373504639],
 'name': 'Boots',
 'type': 'pharmacy'}
{'_id': ObjectId('5aedd8ca6eca7e03326e9fa5'),
 'geocode': [-5.2409105301, 50.027534484899995],
 'name': 'Boots',
 'type': 'pharmacy'}
{'_id': ObjectId('5aedd8ca6eca7e03326e951c'),
 'geocode': [-3.7776679993, 50.282867431599996],
 'name': 'The Co-Operative Pharmacy',
 'type': 'pharmacy'}
{'_id': ObjectId('5aedd8ca6eca7e03326e9f23'),
 'geocode': [-3.7771580219, 50.2834968567],
 'name': 'Boots',
 'type': 'pharmacy'}
{'_id': ObjectId('5aedd8ca6eca7e03326e9dea'),
 'geocode': [-3.7818698882999997, 50.2886314392],
 'name': 'Day Lewis Pharmacy',
 'type': 'pharmacy'}
{'_id': ObjectId('5aedd8ca6eca7e03326ea70d'),
 'geocode': [-6.3088903427, 49.9126358032],
 'name': 'Isles Of Scilly Pharmacy',
 'type': 'pharmacy'}
{'_id': ObjectId('5aedd8ca6eca7e03326e9f74'),
 'geocode': [-5.3156189919, 50.085399627700006],
 'name': 'Boots',
 'type': 'pharmacy'}
{'_id': ObjectId('5aedd8ca6eca7e03326e9053'),
 'geocode': [-5.270141601600001, 50.0996437073],
 'name': "Hall's Pharmacy",
 'type': 'pharmacy'}
{'_id': ObjectId('5aedd8ca6eca7e03326e8c79'),
 'geocode': [-5.2722282410000005, 50.0996856689],
 'name': 'Boots',
 'type': 'pharmacy'}
{'_id': ObjectId('5aedd8ca6eca7e03326e8762'),
 'geocode': [-5.2669582367, 50.1040344238],
 'name': 'Tesco Instore Pharmacy',
 'type': 'pharmacy'}
{'_id': ObjectId('5aedd8ca6eca7e03326e939e'),
 'geocode': [-3.5784521102999998, 50.3513183594],
 'name': 'Boots',
 'type': 'pharmacy'}
{'_id': ObjectId('5aedd8ca6eca7e03326e85db'),
 'geocode': [-3.580780983, 50.3511810303],
 'name': 'Lloydspharmacy',
 'type': 'pharmacy'}
{'_id': ObjectId('5aedd9a76eca7e03326f8816'),
 'geocode': [-1.289514, 50.577883],
 'name': 'Criminal damage and arson',
 'type': 'crime'}
{'_id': ObjectId('5aedd9c56eca7e033271aa82'),
 'date': '2017-05',
 'geocode': [-1.289514, 50.577883],
 'name': 'Criminal damage and arson',
 'type': 'crime'}
{'_id': ObjectId('5aedd9a86eca7e0332705e6a'),
 'geocode': [-1.29091, 50.578953000000006],
 'name': 'Anti-social behaviour',
 'type': 'crime'}
{'_id': ObjectId('5aedd9c66eca7e03327280d6'),
 'date': '2017-08',
 'geocode': [-1.29091, 50.578953000000006],
 'name': 'Anti-social behaviour',
 'type': 'crime'}
{'_id': ObjectId('5aedd9a76eca7e03326ebeea'),
 'geocode': [-1.284365, 50.580298],
 'name': 'Criminal damage and arson',
 'type': 'crime'}
{'_id': ObjectId('5aedd9a76eca7e03326f8815'),
 'geocode': [-1.284365, 50.580298],
 'name': 'Anti-social behaviour',
 'type': 'crime'}
{'_id': ObjectId('5aedd9a86eca7e03326fcec6'),
 'geocode': [-1.284365, 50.580298],
 'name': 'Other theft',
 'type': 'crime'}
{'_id': ObjectId('5aedd9a86eca7e03326fcec9'),
 'geocode': [-1.284365, 50.580298],
 'name': 'Violence and sexual offences',
 'type': 'crime'}
{'_id': ObjectId('5aedd9a86eca7e0332705e6e'),
 'geocode': [-1.284365, 50.580298],
 'name': 'Violence and sexual offences',
 'type': 'crime'}
{'_id': ObjectId('5aedd9c56eca7e033270e156'),
 'date': '2017-02',
 'geocode': [-1.284365, 50.580298],
 'name': 'Criminal damage and arson',
 'type': 'crime'}
{'_id': ObjectId('5aedd9c56eca7e033271aa81'),
 'date': '2017-05',
 'geocode': [-1.284365, 50.580298],
 'name': 'Anti-social behaviour',
 'type': 'crime'}
{'_id': ObjectId('5aedd9c56eca7e033271f132'),
 'date': '2017-06',
 'geocode': [-1.284365, 50.580298],
 'name': 'Other theft',
 'type': 'crime'}
{'_id': ObjectId('5aedd9c56eca7e033271f135'),
 'date': '2017-06',
 'geocode': [-1.284365, 50.580298],
 'name': 'Violence and sexual offences',
 'type': 'crime'}
{'_id': ObjectId('5aedd9c66eca7e03327280da'),
 'date': '2017-08',
 'geocode': [-1.284365, 50.580298],
 'name': 'Violence and sexual offences',
 'type': 'crime'}
{'_id': ObjectId('5aedd9a76eca7e03326efef2'),
 'geocode': [-1.2572860000000001, 50.58226],
 'name': 'Anti-social behaviour',
 'type': 'crime'}
{'_id': ObjectId('5aedd9c56eca7e033271215e'),
 'date': '2017-03',
 'geocode': [-1.2572860000000001, 50.58226],
 'name': 'Anti-social behaviour',
 'type': 'crime'}
{'_id': ObjectId('5aedd9a86eca7e03326fcf04'),
 'geocode': [-1.247212, 50.584245],
 'name': 'Other theft',
 'type': 'crime'}
{'_id': ObjectId('5aedd9c56eca7e033271f170'),
 'date': '2017-06',
 'geocode': [-1.247212, 50.584245],
 'name': 'Other theft',
 'type': 'crime'}

In [ ]:
server.stop()